import Image from "next/image";
import Link from "next/link";
import { BookOpen, CalendarDays, Clock3, Compass, Languages, ShieldCheck, Sun, TicketCheck } from "lucide-react";

const circuits = [
  ["12 Jyotirlingas", "Embark on the spiritual journey to all twelve Jyotirlingas of Lord Shiva.", "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=500&q=80"],
  ["Char Dham Yatra", "Visit Yamunotri, Gangotri, Kedarnath and Badrinath.", "https://images.unsplash.com/photo-1624996752380-8ec242e0f85d?auto=format&fit=crop&w=500&q=80"],
  ["Shakti Peethas", "Journey to the sacred abodes of Goddess across India.", "https://images.unsplash.com/photo-1621847468516-1ed5d0df56fe?auto=format&fit=crop&w=500&q=80"],
];

export default function TempleDirectoryExtras({ section }) {
  if (section === "services") return <section className="mx-auto max-w-7xl px-4 pb-9 sm:px-6 lg:px-8"><div className="grid overflow-hidden rounded-xl bg-gradient-to-r from-[#681b1f] to-[#461014] text-white md:grid-cols-4">{[[TicketCheck,"Today’s Open Temples","1,842 temples open today"],[Sun,"Aarti Timings","Morning, Evening & Special"],[CalendarDays,"Festival Calendar","Upcoming festivals & events"],[Compass,"Travel Guide","Tips for a divine journey"]].map(([Icon,a,b],i)=><div key={a} className={`flex items-center gap-4 p-5 ${i?"md:border-l md:border-white/15":""}`}><Icon className="text-[#d9a545]"/><div><b className="text-sm">{a}</b><p className="mt-1 text-[10px] text-white/70">{b}</p></div><span className="ml-auto">›</span></div>)}</div></section>;
  if (section === "circuits") return <section className="mx-auto max-w-7xl px-4 pb-9 sm:px-6 lg:px-8"><h2 className="mb-5 font-serif text-2xl font-bold text-[#531b1d]">Sacred Pilgrimage Circuits</h2><div className="grid gap-5 md:grid-cols-3">{circuits.map(([a,b,img])=><article key={a} className="flex overflow-hidden rounded-xl border border-[#e5cda9] bg-white"><div className="relative w-2/5 shrink-0"><Image src={img} alt={a} fill className="object-cover"/></div><div className="p-5"><h3 className="font-serif text-lg font-bold text-[#681b1f]">{a}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{b}</p><Link href="/temples" className="mt-5 block text-xs font-bold text-maroon">Explore Route &nbsp; →</Link></div></article>)}</div></section>;
  return <><section className="border-y border-[#ead8c6] bg-[#fff7eb] py-10"><div className="mx-auto max-w-7xl px-4 text-center sm:px-6 lg:px-8"><h2 className="font-serif text-3xl font-bold text-[#5b2020]">Explore India’s Rich Temple Heritage</h2><div className="mx-auto mt-4 h-px w-32 bg-[#d4a24b]"/><div className="mx-auto mt-7 grid max-w-3xl gap-8 text-left md:grid-cols-2"><div><b className="font-serif">Spiritual Legacy</b><p className="mt-2 text-xs leading-6 text-slate-600">India is home to thousands of ancient temples that reflect our rich culture, faith and timeless traditions.</p></div><div className="md:border-l md:border-[#dfcdb9] md:pl-8"><b className="font-serif">Plan Your Divine Journey</b><p className="mt-2 text-xs leading-6 text-slate-600">Discover, plan and experience the divine across India with verified temple information.</p></div></div></div></section></>;
}
